[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri", "./bundle.css"]

[serve]
address = "127.0.0.1"
port = 1420
open = false

[[hooks]]
stage = "pre_build"
command = "stylance"
command_arguments = ["."]
